### PR TITLE
use shibboleth as default and disable user login form in production

### PR DESCRIPTION
**Pull request by weiweishi**
Fixes #issuenumber ; refs #517 #516 #514 #513 

Present tense short summary (50 characters or less)

This is to enable shibboleth authentication as the default in staging/production environment. This change should address the issues mentioned above.  

Changes proposed in this pull request:
* Change in config/settings.yml to add shibboleth as an auth configuration when in production/staging environment

### CODE REVIEW

**Comment by weiweishi** [comment]
@jefferya Good to know. I didn't find this environment variable initially in staging `/etc/httpd/conf/avalon6_env.conf`, so I didn't realize its existence. I'd like to understand more how this is used - sounds like a more proper way of setting environment dependent configurations. 

> Looks good. There might be an alternate means via the environment variable: `SETTINGS__AUTH__CONFIGURATION__PROVIDER`.
> 
> Does fields: :email need to be included in the staging/production scope?

**Comment by weiweishi** [comment]
And with this question: 

> Does fields: :email need to be included in the staging/production scope?

do you mean this:
```
    :params:
      :fields:
      - :email
```
I think this is for the identity authentication? to only require the email field when login?

**Comment by jefferya** [comment]
> 
> 
> @jefferya Good to know. I didn't find this environment variable initially in staging `/etc/httpd/conf/avalon6_env.conf`, so I didn't realize its existence. I'd like to understand more how this is used - sounds like a more proper way of setting environment dependent configurations.

I missed this environment variable in the spec due to a lack of in-depth understanding. My understanding of Avalon 5, the auth path for the login link was changed to point to shib instead of changing the default provider. The latter being a cleaner solution.
 
My understanding, this environment variable is exposed via the `config` Gem from the setting yaml. E.g., https://github.com/ualbertalib/avalon/blob/avalon-6/config/initializers/config.rb

**Comment by weiweishi** [comment]
@jefferya I did some preliminary testing for the configuration with env var SETTINGS__AUTH__CONFIGURATION__PROVIDER, but am unable to figure out the correct syntax yet. So I will merge this as is, so we can address these issues now, and will open a ticket to use the env var properly.

**Pull request merged**
